import '../models/cultural_content.dart';
import '../models/patient_info.dart';
import '../services/db_service.dart';

abstract class PatientFileRepository {
  List<PatientFile> getFiles();
  void addFile(PatientFile file);
  void deleteFile(String id);
}

class LocalPatientFileRepository implements PatientFileRepository {
  @override
  List<PatientFile> getFiles() => DbService().getPatientFiles();

  @override
  void addFile(PatientFile file) {
    DbService().savePatientFile(file);
  }

  @override
  void deleteFile(String id) {
    DbService().deletePatientFile(id);
  }
}

abstract class CulturalContentRepository {
  List<CulturalContentItem> getAllItems();
  CulturalContentItem? getItemById(String id);
}

class LocalCulturalContentRepository implements CulturalContentRepository {
  final List<CulturalContentItem> _items = [
    CulturalContentItem(
      id: 'vemana_padyam_1',
      category: 'Proverb',
      title: 'Vemana Padyam: Uppu Kappurambu (Telugu)',
      originalScriptText: 'ఉప్పు కప్పురంబు నొక్క పోలిక నుండు\nచూడ చూడ రుచుల జాడ వేరు\nపురుషులందు పుణ్య పురుషులు వేరయా\nవిశ్వదాభిరామ వినుర వేమ॥',
      transliteration: 'Uppu kappurambu nokka polika nundu | Chuda chuda ruchula jada veru | Purushulandu punya purushulu veraya | Viswadhabhirama vinura Vema ||',
      englishMeaning: 'Salt and camphor appear identical to the eye. But upon tasting, their true nature is revealed. Likewise, noble human beings stand out by their character.',
      englishExplanation: 'Famous Telugu moral poem by Yogi Vemana fostering sensory comparison and memory retention.',
      cognitivePurpose: 'Sensory discernment & cross-linguistic memory retrieval.',
      chunks: ['ఉప్పు కప్పురంబు', 'నొక్క పోలిక నుండు', 'చూడ చూడ రుచుల', 'జాడ వేరు', 'విశ్వదాభిరామ వినుర వేమ'],
      languageCode: 'te',
    ),
    CulturalContentItem(
      id: 'vamana_padyam',
      category: 'Verse',
      title: 'Vamana Padyam: Intha Thanayai (Telugu)',
      originalScriptText: 'ఇంత తనయై మఱి యింత యై\nనభంబంతయై నభోవీధికి నంతయై\nలక్ష్మికినంతయై దిశల కంతయై\nమఱియు నంతయై భాసిల్లెన్॥',
      transliteration: 'Intha thanayai mari intha yai | Nabhambanthayai nabhoveedhiki nanthayai | Lakshmikinanthayai dishala kanthayai | Mariyu nanthayai bhasillan ||',
      englishMeaning: 'He grew from a small form to encompass the earth, the sky, the cosmos, and beyond infinity.',
      englishExplanation: 'Classic Potana Bhagavatham verse celebrating expanding spatial visualization and auditory scale.',
      cognitivePurpose: 'Spatial expansion visualization & verbal rhythm precision.',
      chunks: ['ఇంత తనయై మఱి యింత యై', 'నభంబంతయై నభోవీధికి', 'లక్ష్మికినంతయై దిశల కంతయై', 'మఱియు నంతయై భాసిల్లెన్'],
      languageCode: 'te',
    ),
    CulturalContentItem(
      id: 'kabir_doha_dheere',
      category: 'Proverb',
      title: 'Kabir Doha: Dheere Dheere Re Mana (Hindi)',
      originalScriptText: 'धीरे-धीरे रे मना, धीरे सब कुछ होय।\nमाली सींचे सौ घड़ा, ॠतु आये फल होय॥',
      transliteration: 'Dheere-dheere re mana, dheere sab kuchh hoy | Mali seenche sau ghada, ritu aaye phal hoy ||',
      englishMeaning: 'Slowly and steadily, O mind, everything comes to fruition. The gardener waters with a hundred pots, but fruit arrives only in season.',
      englishExplanation: 'Sant Kabir couplet encouraging patient practice and cognitive persistence.',
      cognitivePurpose: 'Semantic memory retrieval & self-regulation.',
      chunks: ['धीरे-धीरे रे मना', 'धीरे सब कुछ होय', 'माली सींचे सौ घड़ा', 'ॠतु आये फल होय'],
      languageCode: 'hi',
    ),
    CulturalContentItem(
      id: 'tulsi_doha_daya',
      category: 'Proverb',
      title: 'Tulsi Doha: Daya Dharma Ka Mool Hai (Hindi)',
      originalScriptText: 'दया धर्म का मूल है, पाप मूल अभिमान।\nतुलसी दया न छोड़िये, जब लग घट में प्राण॥',
      transliteration: 'Daya dharma ka mool hai, paap mool abhimaan | Tulsi daya na chhodiye, jab lag ghat mein praan ||',
      englishMeaning: 'Compassion is the root of righteousness, while pride is the root of sin. Never abandon compassion as long as breath remains.',
      englishExplanation: 'Goswami Tulsidas doha emphasizing ethical anchor and rhythmic balance.',
      cognitivePurpose: 'Verbal anchor recall & moral phrase integration.',
      chunks: ['दया धर्म का मूल है', 'पाप मूल अभिमान', 'तुलसी दया न छोड़िये', 'जब लग घट में प्राण'],
      languageCode: 'hi',
    ),
    CulturalContentItem(
      id: 'thirukkural_1',
      category: 'Proverb',
      title: 'Thirukkural: Agara Mudhala (Tamil)',
      originalScriptText: 'அகர முதல எழுத்தெல்லாம் ஆதி\nபகவன் முதற்றே உலகு.',
      transliteration: 'Agara mudhala ezhutthellam aadhi | Bhagavan mudhattre ulagu.',
      englishMeaning: 'As the letter \'A\' is the beginning of all letters, so the Divine Primordial Lord is the origin of the universe.',
      englishExplanation: 'Opening verse of Thiruvalluvar\'s Thirukkural, widely recited across South India.',
      cognitivePurpose: 'Symbolic sequence origin recall & rhythm retention.',
      chunks: ['அகர முதல எழுத்தெல்லாம்', 'ஆதி பகவன்', 'முதற்றே உலகு'],
      languageCode: 'ta',
    ),
    CulturalContentItem(
      id: 'o_mor_apunar_desh',
      category: 'Song',
      title: 'O Mor Apunar Desh (Assamese Folk Song)',
      originalScriptText: 'অ\' মোৰ আপোনাৰ দেশ\nঅ\' মোৰ চিকුණী দেশ\nএনেখন সুৱলা, এনেখন সুফলা\nএনেখন মৰমৰ দেশ।',
      transliteration: 'O mor apunar desh | O mor chikuni desh | Enekhon suwola, enekhon sufola | Enekhon moromor desh.',
      englishMeaning: 'O my endearing land, O my pristine land! Such a sweet land, such a fruitful land, such a beloved land of mine.',
      englishExplanation: 'Assamese state song by Sahityarathi Lakshminath Bezbaroa evoking North Eastern cultural identity.',
      cognitivePurpose: 'Regional auditory emotion & speech fluency activation.',
      chunks: ['অ\' মোৰ আপোনাৰ দেশ', 'অ\' মোৰ চিকුණী দেশ', 'এনেখন সুৱলা, এনেখন সুফলা', 'এনেখন মৰমৰ দেশ'],
      languageCode: 'as',
    ),
    CulturalContentItem(
      id: 'amader_chhoto_nodi',
      category: 'Rhyme',
      title: 'Amader Chhoto Nodi (Bengali Poem)',
      originalScriptText: 'আমাদের ছোট নদী চলে বাঁকে বাঁকে\nবৈশাখ মাসে তার হাঁটু জল থাকে।\nপার হয়ে যায় গোরু, পার হয় গাড়ি,\nদুই ধার উঁচু তার, ঢালু তার পাড়ি।',
      transliteration: 'Amader chhoto nodi chole bake bake | Boishakh mase tar hatu jol thake. | Par hoye jay goru, par hoy gari, | Dui dhar uchu tar, dhalu tar pari.',
      englishMeaning: 'Our little river flows in twists and turns. In the month of Boishakh it has knee-deep water. Cows and carts cross over easily.',
      englishExplanation: 'Classic Rabindranath Tagore poem for childhood speech resonance and rhythm.',
      cognitivePurpose: 'Sequential auditory cadence & articulation fluidity.',
      chunks: ['আমাদের ছোট নদী चले বাঁকে বাঁকে', 'বৈশাখ মাসে তার হাঁটু জল থাকে', 'পার হয়ে যায় গোরু, পার হয় গাড়ি', 'দুই ধার উঁচু তার, ঢালু তার পাড়ি'],
      languageCode: 'bn',
    ),
    CulturalContentItem(
      id: 'twinkle_star',
      category: 'Rhyme',
      title: 'Twinkle Twinkle Little Star (Childhood Rhyme)',
      originalScriptText: 'Twinkle, twinkle, little star,\nHow I wonder what you are!\nUp above the world so high,\nLike a diamond in the sky.',
      transliteration: 'Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky.',
      englishMeaning: 'Universal childhood poem invoking early auditory neural patterns.',
      englishExplanation: 'Classic nursery rhyme for motor-auditory memory retrieval and sentence cadence.',
      cognitivePurpose: 'Early childhood auditory memory activation.',
      chunks: ['Twinkle, twinkle, little star', 'How I wonder what you are', 'Up above the world so high', 'Like a diamond in the sky'],
      languageCode: 'en',
    ),
    CulturalContentItem(
      id: 'family_memory_home',
      category: 'Story',
      title: 'Family Story: Grandfather\'s House in Vizag',
      originalScriptText: 'Our ancestral home stood near the beach in Vizag.\nEvery morning we walked along the coast at sunrise.\nGrandma cooked fresh coconut chutney and dosas.\nThe family gathered every festival under the banyan tree.',
      transliteration: 'Our ancestral home stood near the beach in Vizag. Every morning we walked along the coast at sunrise...',
      englishMeaning: 'Personalized family memory anchor for meaningful long-term recall.',
      englishExplanation: 'Caregiver-provided memory recall template for familiar personal identity grounding.',
      cognitivePurpose: 'Personal episodic memory & identity anchoring.',
      chunks: [
        'Our ancestral home stood near the beach in Vizag',
        'Every morning we walked along the coast at sunrise',
        'Grandma cooked fresh coconut chutney and dosas',
        'The family gathered every festival under the banyan tree'
      ],
      languageCode: 'en',
    ),
    CulturalContentItem(
      id: 'gayatri_mantra',
      category: 'Mantra',
      title: 'Gayatri Mantra (Universal Vedic Illumination)',
      originalScriptText: 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्॥',
      transliteration: 'Oṁ Bhūr Bhuvaḥ Svaḥ Tat Savitur Vareṇyaṁ Bhargo Devasya Dhīmahi Dhiyo Yo Naḥ Pracodayāt',
      englishMeaning: 'We meditate on the supreme effulgence of the Divine Sun. May that Divine Light awaken and guide our intellect.',
      englishExplanation: 'Rigveda 3.62.10. Foundational 24-syllable solar hymn used for auditory memory and 3-chunk rhythm retention.',
      cognitivePurpose: 'Auditory sequential working memory & 3-chunk rhythm retention.',
      chunks: ['ॐ भूर्भुवः स्वः', 'तत्सवितुर्वरेण्यं', 'भर्गो देवस्य धीमहि', 'धियो यो नः प्रचोदयात्'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'mahamrityunjaya_mantra',
      category: 'Mantra',
      title: 'Mahamrityunjaya Mantra (Healing & Vitality)',
      originalScriptText: 'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् । उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात् ॥',
      transliteration: 'Oṁ Tryambakaṁ Yajāmahe Sugandhiṁ Puṣṭi-Vardhanam | Urvārukam-Iva Bandhanān Mṛtyor-Mukṣīya Mā\'mṛtāt ||',
      englishMeaning: 'We worship the Three-Eyed Lord, who is fragrant and nourishes all beings. As a ripe melon detaches effortlessly from its vine, free us from mortality.',
      englishExplanation: 'Rigveda 7.59.12. Celebrated Vedic healing verse fostering breath pacing and rhythmic confidence.',
      cognitivePurpose: 'Rhythmic breath regulation & multi-syllable phoneme recall.',
      chunks: ['ॐ त्र्यम्बकं यजामहे', 'सुगन्धिं पुष्टिवर्धनम्', 'उर्वारुकमिव बन्धनात्', 'मृत्योर्मुक्षीय माऽमृतात्'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'shanti_mantra',
      category: 'Verse',
      title: 'Shanti Mantra: Saha Navavatu (Harmony & Peace)',
      originalScriptText: 'ॐ सह नाववतु सह नौ भुनक्तु सह वीर्यं करवावहै । तेजस्वि नावधीतमस्तु मा विद्विषावहै ॥ ॐ शान्तिः शान्तिः शान्तिः ॥',
      transliteration: 'Oṁ Saha Nāvavatu Saha Nau Bhunaktu Saha Vīryaṁ Karavāvahai | Tejasvi Nāvadhītam-Astu Mā Vidviṣāvahai || Oṁ Śāntiḥ Śāntiḥ Śāntiḥ ||',
      englishMeaning: 'May the Divine protect us both (teacher and student). May He nourish us both. May we work together with great energy. May our learning be brilliant. May there be no hatred between us.',
      englishExplanation: 'Taittiriya Upanishad peace invocation reinforcing paired auditory cadence and group memory.',
      cognitivePurpose: 'Paired auditory cadence & prosodic peace recall.',
      chunks: ['ॐ सह नाववतु', 'सह नौ भुनक्तु', 'सह वीर्यं करवावहै', 'तेजस्वि नावधीतमस्तु', 'मा विद्विषावहै', 'ॐ शान्तिः शान्तिः शान्तिः'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'vakratunda_mantra',
      category: 'Mantra',
      title: 'Vakratunda Mahakaya (Obstacle Removal & Focus)',
      originalScriptText: 'वक्रतुण्ड महाकाय सूर्यकोटिसमप्रभ । निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा ॥',
      transliteration: 'Vakratuṇḍa Mahākāya Sūryakoṭi Samaprabha | Nirvighnaṁ Kuru Me Deva Sarva-Kāryeṣu Sarvadā ||',
      englishMeaning: 'O Lord with the curved trunk and immense form, shining with the brilliance of a million suns, please make all my endeavors free of obstacles always.',
      englishExplanation: 'Classic Sanskrit verse recited before starting daily tasks to focus intention and working memory.',
      cognitivePurpose: 'Task-initiation mental focus & structured phrase articulation.',
      chunks: ['वक्रतुण्ड महाकाय', 'सूर्यकोटिसमप्रभ', 'निर्विघ्नं कुरु मे देव', 'सर्वकार्येषु सर्वदा'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'asato_ma_mantra',
      category: 'Verse',
      title: 'Asato Ma Sadgamaya (Lead Me From Darkness to Light)',
      originalScriptText: 'ॐ असतो मा सद्गमय । तमसो मा ज्योतिर्गमय । मृत्योर्मा अमृतं गमय ॥ ॐ शान्तिः शान्तिः शान्तिः ॥',
      transliteration: 'Oṁ Asato Mā Sad-Gamaya | Tamaso Mā Jyotir-Gamaya | Mṛtyor-Mā Amṛtaṁ Gamaya || Oṁ Śāntiḥ Śāntiḥ Śāntiḥ ||',
      englishMeaning: 'Lead me from falsehood to truth. Lead me from darkness to light. Lead me from death to immortality. Om peace, peace, peace.',
      englishExplanation: 'Brihadaranyaka Upanishad verse fostering philosophical recall and triple parallel structure memory.',
      cognitivePurpose: 'Triple-parallel semantic contrast & calm emotional resonance.',
      chunks: ['ॐ असतो मा सद्गमय', 'तमसो मा ज्योतिर्गमय', 'मृत्योर्मा अमृतं गमय', 'ॐ शान्तिः शान्तिः शान्तिः'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'purusha_suktam_opening',
      category: 'Verse',
      title: 'Purusha Suktam Opening (Cosmic Awareness)',
      originalScriptText: 'ॐ सहस्रशीर्षा पुरुषः सहस्राक्षः सहस्रपात् । स भूमिं विश्वतो वृत्वात्यतिष्ठद्दशाङ्गुलम् ॥',
      transliteration: 'Oṁ Sahasra-Śīrṣā Puruṣaḥ Sahasrākṣaḥ Sahasra-Pāt | Sa Bhūmiṁ Viśvato Vṛtvā-Tyatiṣṭhad Daśāṅgulam ||',
      englishMeaning: 'The Cosmic Being has thousands of heads, eyes, and feet. Encompassing the Earth on all sides, He transcends it by ten fingers.',
      englishExplanation: 'Rigveda 10.90 opening verse for advanced spatial-auditory memory and rhythmic chanting.',
      cognitivePurpose: 'Cosmic spatial expansion memory & complex compound phoneme recall.',
      chunks: ['ॐ सहस्रशीर्षा पुरुषः', 'सहस्राक्षः सहस्रपात्', 'स भूमिं विश्वतो वृत्वा', 'अत्यतिष्ठद्दशाङ्गुलम्'],
      languageCode: 'sa',
    ),

    // --- SANSKRIT ADDITIONS ---
    CulturalContentItem(
      id: 'guru_brahma_shloka',
      category: 'Shloka',
      title: 'Guru Brahma Guru Vishnu (Universal Reverence)',
      originalScriptText: 'गुरुर्ब्रह्मा गुरुर्विष्णुः गुरुर्देवो महेश्वरः । गुरुः साक्षात् परं ब्रह्म तस्मै श्रीगुरवे नमः ॥',
      transliteration: 'Gurur Brahmā Gurur Viṣṇuḥ Gurur Devo Maheśvaraḥ | Guruḥ Sākṣāt Paraṁ Brahma Tasmai Śrī-Gurave Namaḥ ||',
      englishMeaning: 'The Guru is Brahma, the Guru is Vishnu, the Guru is Shiva. The Guru is verily the supreme Brahman. Salutations to that holy Guru.',
      englishExplanation: 'Traditional reverence shloka honoring guiding lights in life, aiding memory sequencing and gratitude.',
      cognitivePurpose: 'Teacher gratitude & quad-meter syllable recall.',
      chunks: ['गुरुर्ब्रह्मा गुरुर्विष्णुः', 'गुरुर्देवो महेश्वरः', 'गुरुः साक्षात् परं ब्रह्म', 'तस्मै श्रीगुरवे नमः'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'saraswati_namastubhyam',
      category: 'Shloka',
      title: 'Saraswati Vandana (Knowledge & Articulation)',
      originalScriptText: 'सरस्वति नमस्तुभ्यं वरदे कामरूपिणि । विद्यारम्भं करिष्यामि सिद्धिर्भवतु मे सदा ॥',
      transliteration: 'Sarasvati Namastubhyaṁ Varade Kāmarūpiṇi | Vidyārambhaṁ Kariṣyāmi Siddhir Bhavatu Me Sadā ||',
      englishMeaning: 'Salutations to Goddess Saraswati, the granter of boons. As I begin my learning, may I always achieve wisdom and accomplishment.',
      englishExplanation: 'Classical prayer before studies strengthening vocal clarity and sequential articulation.',
      cognitivePurpose: 'Speech clarity, articulation & memory activation.',
      chunks: ['सरस्वति नमस्तुभ्यं', 'वरदे कामरूपिणि', 'विद्यारम्भं करिष्यामि', 'सिद्धिर्भवतु मे सदा'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'sarve_bhavantu_sukhinah',
      category: 'Verse',
      title: 'Sarve Bhavantu Sukhinah (Universal Harmony)',
      originalScriptText: 'सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः । सर्वे भद्राणि पश्यन्तु मा कश्चिद्दुःखभाग्भवेत् ॥ ॐ शान्तिः शान्तिः शान्तिः ॥',
      transliteration: 'Sarve Bhavantu Sukhinaḥ Sarve Santu Nirāmayāḥ | Sarve Bhadrāṇi Paśyantu Mā Kaścid Duḥkha-Bhāgbhavet || Oṁ Śāntiḥ Śāntiḥ Śāntiḥ ||',
      englishMeaning: 'May all beings be happy; may all be free from illness; may all see what is good and auspicious; may no one suffer grief. Om Peace, Peace, Peace.',
      englishExplanation: 'Universal benediction from the Brihadaranyaka Upanishad generating positive emotional grounding.',
      cognitivePurpose: 'Social-emotional empathy & peaceful rhythmic cadence.',
      chunks: ['सर्वे भवन्तु सुखिनः', 'सर्वे सन्तु निरामयाः', 'सर्वे भद्राणि पश्यन्तु', 'मा कश्चिद्दुःखभाग्भवेत्', 'ॐ शान्तिः शान्तिः शान्तिः'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'tvameva_mata_shloka',
      category: 'Shloka',
      title: 'Tvameva Mata Cha Pita (Devotional Surrender)',
      originalScriptText: 'त्वमेव माता च पिता त्वमेव त्वमेव बन्धुश्च सखा त्वमेव । त्वमेव विद्या द्रविणं त्वमेव त्वमेव सर्वं मम देव देव ॥',
      transliteration: 'Tvameva Mātā Ca Pitā Tvameva Tvameva Bandhuśca Sakhā Tvameva | Tvameva Vidyā Draviṇaṁ Tvameva Tvameva Sarvaṁ Mama Deva Deva ||',
      englishMeaning: 'You alone are my mother and my father. You alone are my relative and my companion. You alone are knowledge and wealth. You are everything to me, O Supreme One.',
      englishExplanation: 'Beloved devotional prayer cultivating deep comforting safety and emotional stability.',
      cognitivePurpose: 'Episodic relational memory & comforting cadence.',
      chunks: ['त्वमेव माता च पिता त्वमेव', 'त्वमेव बन्धुश्च सखा त्वमेव', 'त्वमेव विद्या द्रविणं त्वमेव', 'त्वमेव सर्वं मम देव देव'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'karagre_vasate_lakshmi',
      category: 'Shloka',
      title: 'Karagre Vasate Lakshmi (Morning Palm Contemplation)',
      originalScriptText: 'कराग्रे वसते लक्ष्मीः करमध्ये सरस्वती । करमूले तु गोविन्दः प्रभाते करदर्शनम् ॥',
      transliteration: 'Karāgre Vasate Lakṣmīḥ Karamadhye Sarasvatī | Karamūle Tu Govindaḥ Prabhāte Karadarśanam ||',
      englishMeaning: 'At the tips of the fingers resides Lakshmi; in the palm resides Saraswati; at the base rests Govinda. Looking at one\'s palms at dawn awakens the day with clarity.',
      englishExplanation: 'Morning awakening verse linking motor sensation with daily mindful routine recall.',
      cognitivePurpose: 'Morning sensory-motor hand orientation & tactile recall.',
      chunks: ['कराग्रे वसते लक्ष्मीः', 'करमध्ये सरस्वती', 'करमूले तु गोविन्दः', 'प्रभाते करदर्शनम्'],
      languageCode: 'sa',
    ),
    CulturalContentItem(
      id: 'gita_yada_yada_hi',
      category: 'Shloka',
      title: 'Yada Yada Hi Dharmasya (Bhagavad Gita 4.7)',
      originalScriptText: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत । अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम् ॥',
      transliteration: 'Yadā Yadā Hi Dharmasya Glānir Bhavati Bhārata | Abhyutthānam Adharmasya Tadātmānaṁ Sṛjāmyaham ||',
      englishMeaning: 'Whenever there is a decline in righteousness and a rise in unrighteousness, O Arjuna, I manifest Myself on Earth.',
      englishExplanation: 'Foundational Gita shloka familiar to millions, providing strong cultural resonance and meter recall.',
      cognitivePurpose: 'Historical philosophical retrieval & anustubh meter recall.',
      chunks: ['यदा यदा हि धर्मस्य', 'ग्लानिर्भवति भारत', 'अभ्युत्थानमधर्मस्य', 'तदात्मानं सृजाम्यहम्'],
      languageCode: 'sa',
    ),

    // --- TELUGU ADDITIONS ---
    CulturalContentItem(
      id: 'sumati_aakali',
      category: 'Proverb',
      title: 'Sumati Shatakam: Aakali Ruchi Yerugadu (Telugu)',
      originalScriptText: 'ఆకలి రుచి యెఱుఁగదు, నిద్ర సుఖ మెఱుఁగదు\nవలపు బిడియ మెఱుఁగదు, పిఱికి తలపడ నెఱుఁగదు\nఅని యెఱుక గల సుమతీ॥',
      transliteration: 'Aakali ruchi yerugadu, nidra sukha merugadu | Valapu bidiya merugadu, piriki talapada nerugadu | Ani yeruka gala sumathi ||',
      englishMeaning: 'Hunger knows no fine taste; deep exhaustion knows no bed; genuine love knows no shyness; courage knows no fear of trial. Understand this, O wise mind.',
      englishExplanation: 'Famous moral poem from Baddena\'s Sumati Shatakam training contrasting parallel phrases.',
      cognitivePurpose: 'Contrast comparison & everyday experiential recall.',
      chunks: ['ఆకలి రుచి యెఱుఁగదు', 'నిద్ర సుఖ మెఱుఁగదు', 'వలపు బిడియ మెఱుఁగదు', 'అని యెఱుక గల సుమతీ'],
      languageCode: 'te',
    ),
    CulturalContentItem(
      id: 'sumati_epurana',
      category: 'Proverb',
      title: 'Sumati Shatakam: Eppati Keyyadi Prastuta (Telugu)',
      originalScriptText: 'ఎప్పటి కెయ్యది ప్రస్తుత\nమప్పటి కా మాటలాడి యన్యుల మనముల్\nనొప్పింపక తానొవ్వక\nతప్పించుక తిరుగువాఁడె ధన్యుఁడు సుమతీ॥',
      transliteration: 'Eppati keyyadi prastuta | Mappati kaa maatalaadi yanyula manamul | Noppimpaka taanovvaka | Tappinchuka tiruguvaade dhanyudu sumathi ||',
      englishMeaning: 'Speaking gently according to the time and circumstance, without hurting others\' feelings or harming oneself—such a person is truly blessed.',
      englishExplanation: 'Classic ethical verse cultivating contextual conversation recall and harmony.',
      cognitivePurpose: 'Social awareness, situational nuance & verbal memory.',
      chunks: ['ఎప్పటి కెయ్యది ప్రస్తుత', 'మప్పటి కా మాటలాడి', 'నొప్పింపక తానొవ్వక', 'ధన్యుఁడు సుమతీ'],
      languageCode: 'te',
    ),
    CulturalContentItem(
      id: 'vemana_ganga_paru',
      category: 'Proverb',
      title: 'Vemana Padyam: Ganga Paru Reethi (Telugu)',
      originalScriptText: 'గంగ పారు రీతి కదలి పోవును పుణ్యుఁ\nడల్ప మతియు పారు నల్లకల్లోలమై\nముత్య మగ్గమైన రత్నంబు రీతిరా\nవిశ్వదాభిరామ వినుర వేమ॥',
      transliteration: 'Ganga paru reethi kadali povunu punyud | Alpa matiyu paru nallakallolamai | Muthya maggamaina ratnambu reethira | Viswadhabhirama vinura Vema ||',
      englishMeaning: 'The noble person flows with serene depth like the Ganges. The shallow mind creates noisy turbulence. A pearl is subtle yet priceless.',
      englishExplanation: 'Yogi Vemana couplet contrasting depth and superficiality with memorable river imagery.',
      cognitivePurpose: 'Auditory imagery comparison & metaphor association.',
      chunks: ['గంగ పారు రీతి కదలి పోవును', 'అల్ప మతియు పారు నల్లకల్లోలమై', 'ముత్య మగ్గమైన రత్నంబు రీతిరా', 'విశ్వదాభిరామ వినుర వేమ'],
      languageCode: 'te',
    ),
    CulturalContentItem(
      id: 'potana_siri_thaa',
      category: 'Verse',
      title: 'Potana Bhagavatham: Siri Thaa Vachina (Telugu)',
      originalScriptText: 'సిరి తా వచ్చిన వచ్చును\nసలలితముగ నారికేళ సలిలము భంగిన్\nసిరి తా బోయిన బోవును\nకరి మ్రింగిన వెలగపండు కరణిని సుమతీ॥',
      transliteration: 'Siri thaa vachina vachunu | Salalithamuga naarikela salilamu bhangin | Siri thaa boyina bovunu | Kari mringina velagapandu karanin sumathi ||',
      englishMeaning: 'Fortune enters unnoticed like water filling inside a green coconut. Fortune leaves imperceptibly like the hollow inside a fruit eaten by an elephant.',
      englishExplanation: 'Metaphorical Telugu poem comparing nature\'s quiet patterns with life events.',
      cognitivePurpose: 'Nature-metaphor retention & visual-semantic pairing.',
      chunks: ['సిరి తా వచ్చిన వచ్చును', 'సలలితముగ నారికేళ సలిలము భంగిన్', 'సిరి తా బోయిన బోవును', 'కరి మ్రింగిన వెలగపండు కరణిని'],
      languageCode: 'te',
    ),
    CulturalContentItem(
      id: 'dasarathi_kanchugantu',
      category: 'Verse',
      title: 'Dasarathi Shatakam: Kanti Nakhila Loka (Telugu)',
      originalScriptText: 'కంటి నఖిల లోకైక శరణ్యుని\nకంటి రఘుకుల తిలకుని దాశరథిన్\nకంటి సీతా మనోహరుని కంటిన్\nకంటి కంటి నా కన్నుల పండువుగన్॥',
      transliteration: 'Kanti nakhila lokaika sharanyuni | Kanti raghukula tilakuni dasarathin | Kanti Seetha manoharuni kantin | Kanti kanti naa kannula panduvugan ||',
      englishMeaning: 'I beheld the supreme shelter of all worlds! I beheld Dasharathi, ornament of the Raghu clan! I beheld the beloved of Sita as a grand festival for my eyes!',
      englishExplanation: 'Ramadasu\'s euphoric devotional verse repeating "kanti" (I saw) for rhythmic and visual anchoring.',
      cognitivePurpose: 'Repetitive visual-verbal echo & euphoric rhythmic anchoring.',
      chunks: ['కంటి నఖిల లోకైక శరణ్యుని', 'కంటి రఘుకుల తిలకుని దాశరథిన్', 'కంటి సీతా మనోహరుని కంటిన్', 'నా కన్నుల పండువుగన్'],
      languageCode: 'te',
    ),
    CulturalContentItem(
      id: 'vemana_cheppaloni',
      category: 'Proverb',
      title: 'Vemana Padyam: Cheppaloni Raayi (Telugu)',
      originalScriptText: 'చెప్పులోని రాయి చెవిలోని జోరీగ\nకంటిలోని నలుసు కాలి ముల్లు\nయింటిలోని పోరు యింతింత గాదయ్యా\nవిశ్వదాభిరామ వినుర వేమ॥',
      transliteration: 'Cheppaloni raayi cheviloni joreega | Kantiloni nalusu kaali mullu | Yintiloni poru yintintha gaadayya | Viswadhabhirama vinura Vema ||',
      englishMeaning: 'A pebble in the shoe, a buzzing insect in the ear, a mote of dust in the eye, or a thorn in the heel cause endless agitation. Domestic friction is equally disruptive.',
      englishExplanation: 'Everyday sensory discomforts used as memorable metaphors for household peace.',
      cognitivePurpose: 'Physical sensory listing & sequential memory drill.',
      chunks: ['చెప్పులోని రాయి చెవిలోని జోరీగ', 'కంటిలోని నలుసు కాలి ముల్లు', 'యింటిలోని పోరు యింతింత గాదయ్యా', 'విశ్వదాభిరామ వినుర వేమ'],
      languageCode: 'te',
    ),

    // --- HINDI ADDITIONS ---
    CulturalContentItem(
      id: 'kabir_bada_hua',
      category: 'Proverb',
      title: 'Kabir Doha: Bada Hua To Kya Hua (Hindi)',
      originalScriptText: 'बड़ा हुआ तो क्या हुआ, जैसे पेड़ खजूर।\nपंथी को छाया नहीं, फल लागे अति दूर॥',
      transliteration: 'Bada hua to kya hua, jaise ped khajoor | Panthi ko chhaya nahin, phal laage ati door ||',
      englishMeaning: 'What is the virtue of growing tall like a date palm? It offers no shade to travelers and its fruit is out of reach. True greatness lies in usefulness.',
      englishExplanation: 'Timeless Sant Kabir couplet promoting humility and community service.',
      cognitivePurpose: 'Metaphoric evaluation & couplet antithesis recall.',
      chunks: ['बड़ा हुआ तो क्या हुआ', 'जैसे पेड़ खजूर', 'पंथी को छाया नहीं', 'फल लागे अति दूर'],
      languageCode: 'hi',
    ),
    CulturalContentItem(
      id: 'rahim_dhaga_prem',
      category: 'Proverb',
      title: 'Rahim Doha: Rahiman Dhaga Prem Ka (Hindi)',
      originalScriptText: 'रहिमन धागा प्रेम का, मत तोड़ो चटकाय।\nटूटे पे फिर ना जुड़े, जुड़े गाँठ परि जाय॥',
      transliteration: 'Rahiman dhaaga prem ka, mat todo chatkaay | Toote pe phir na jude, jude gaanth pari jaay ||',
      englishMeaning: 'Rahim advises: do not snap the precious thread of affection impulsively. Once severed, it cannot be tied without leaving a knot.',
      englishExplanation: 'Classic Rahim couplet preserving family relationship awareness.',
      cognitivePurpose: 'Interpersonal empathy & sequence of consequence recall.',
      chunks: ['रहिमन धागा प्रेम का', 'मत तोड़ो चटकाय', 'टूटे पे फिर ना जुड़े', 'जुड़े गाँठ परि जाय'],
      languageCode: 'hi',
    ),
    CulturalContentItem(
      id: 'kabir_pothi_padhi',
      category: 'Proverb',
      title: 'Kabir Doha: Pothi Padhi Padhi Jag Mua (Hindi)',
      originalScriptText: 'पोथी पढ़ि पढ़ि जग मुआ, पंडित भया न कोय।\nढाई आखर प्रेम का, पढ़े सो पंडित होय॥',
      transliteration: 'Pothi padhi padhi jag mua, pandit bhaya na koy | Dhaai aakhar prem ka, padhe so pandit hoy ||',
      englishMeaning: 'Countless books were read through generations without producing true wisdom. He who understands the two-and-a-half letters of Love is truly learned.',
      englishExplanation: 'Celebrated Kabir verse on the essence of heart wisdom over mechanical memorization.',
      cognitivePurpose: 'Semantic essence simplification & syllable cadence.',
      chunks: ['पोथी पढ़ि पढ़ि जग मुआ', 'पंडित भया न कोय', 'ढाई आखर प्रेम का', 'पढ़े सो पंडित होय'],
      languageCode: 'hi',
    ),
    CulturalContentItem(
      id: 'tulsi_mangal_bhavan',
      category: 'Verse',
      title: 'Ramcharitmanas: Mangal Bhavan Amangal Hari (Hindi)',
      originalScriptText: 'मंगल भवन अमंगल हारी।\nद्रवहु सुदसरथ अजिर बिहारी॥\nराम सिया राम सिया राम जय जय राम॥',
      transliteration: 'Mangal bhavan amangal haari | Dravahu sudasarath ajira bihaari | Ram Siya Ram Siya Ram Jai Jai Ram ||',
      englishMeaning: 'O abode of auspiciousness and destroyer of misfortune, who played in the courtyard of King Dasharatha, bless us with eternal peace.',
      englishExplanation: 'Most beloved Ramcharitmanas chaupai in North India, inducing immediate calm and familiarity.',
      cognitivePurpose: 'Devotional auditory echo & rhythmic breath synchronization.',
      chunks: ['मंगल भवन अमंगल हारी', 'द्रवहु सुदसरथ अजिर बिहारी', 'राम सिया राम सिया राम', 'जय जय राम'],
      languageCode: 'hi',
    ),
    CulturalContentItem(
      id: 'surdas_maiya_mori',
      category: 'Song',
      title: 'Surdas Pad: Maiya Mori Main Nahin Makhan Khayo (Hindi)',
      originalScriptText: 'मैया मोरी मैं नहीं माखन खायो।\nभोर भयो गैयन के पाछे, मधुबन मोहि पठायो॥\nचार पहर बंसीबट भटक्यो, साँझ परे घर आयो॥',
      transliteration: 'Maiya mori main nahin maakhan khaayo | Bhor bhayo gaiyan ke paachhe, madhuban mohi pathaayo | Chaar pahar bansibat bhatkyo, saanjh pare ghar aayo ||',
      englishMeaning: 'Mother dear, I did not eat the butter! At daybreak you sent me to the woods behind the calves; I grazed them till dusk before returning home.',
      englishExplanation: 'Charming childhood Krishna pad by Bhakta Surdas evoking maternal tenderness and storytelling.',
      cognitivePurpose: 'Childhood storytelling retrieval & conversational narrative.',
      chunks: ['मैया मोरी मैं नहीं माखन खायो', 'भोर भयो गैयन के पाछे', 'मधुबन मोहि पठायो', 'साँझ परे घर आयो'],
      languageCode: 'hi',
    ),
    CulturalContentItem(
      id: 'bachchan_koshish',
      category: 'Poem',
      title: 'Koshish Karne Walon Ki (Hindi Inspiring Verse)',
      originalScriptText: 'लहरों से डर कर नौका पार नहीं होती,\nकोशिश करने वालों की कभी हार नहीं होती।\nनन्हीं चींटी जब दाना लेकर चलती है,\nचढ़ती दीवारों पर, सौ बार फिसलती है॥',
      transliteration: 'Lahron se dar kar nauka paar nahin hoti, Koshish karne walon ki kabhi haar nahin hoti. Nanhi cheenti jab daana lekar chalti hai, Chadhti deewaron par, sau baar phisalti hai.',
      englishMeaning: 'A boat cannot cross the rough seas out of fear; those who persist never truly fail. When a tiny ant climbs carrying a grain, she slips a hundred times yet succeeds.',
      englishExplanation: 'Famous motivational poem by Harivansh Rai Bachchan inspiring determination and cognitive grit.',
      cognitivePurpose: 'Resilience mindset & narrative episodic recall.',
      chunks: ['लहरों से डर कर नौका पार नहीं होती', 'कोशिश करने वालों की कभी हार नहीं होती', 'नन्हीं चींटी जब दाना लेकर चलती है', 'चढ़ती दीवारों पर सौ बार फिसलती है'],
      languageCode: 'hi',
    ),

    // --- ENGLISH ADDITIONS ---
    CulturalContentItem(
      id: 'wordsworth_daffodils',
      category: 'Poem',
      title: 'Daffodils: I Wandered Lonely as a Cloud (English)',
      originalScriptText: 'I wandered lonely as a cloud\nThat floats on high o\'er vales and hills,\nWhen all at once I saw a crowd,\nA host, of golden daffodils;\nBeside the lake, beneath the trees,\nFluttering and dancing in the breeze.',
      transliteration: 'I wandered lonely as a cloud That floats on high o\'er vales and hills, When all at once I saw a crowd, A host, of golden daffodils...',
      englishMeaning: 'William Wordsworth recollects the uplifting sight of golden daffodils dancing beside a sparkling lake, bringing lasting solace to the quiet mind.',
      englishExplanation: 'Beloved English lyric poem activating nature imagery and reflective memory.',
      cognitivePurpose: 'Mental landscape visualization & positive reminiscing.',
      chunks: ['I wandered lonely as a cloud', 'That floats on high o\'er vales and hills', 'When all at once I saw a crowd', 'A host, of golden daffodils', 'Fluttering and dancing in the breeze'],
      languageCode: 'en',
    ),
    CulturalContentItem(
      id: 'frost_stopping_by_woods',
      category: 'Poem',
      title: 'Stopping by Woods on a Snowy Evening (English)',
      originalScriptText: 'The woods are lovely, dark and deep,\nBut I have promises to keep,\nAnd miles to go before I sleep,\nAnd miles to go before I sleep.',
      transliteration: 'The woods are lovely, dark and deep, But I have promises to keep, And miles to go before I sleep, And miles to go before I sleep.',
      englishMeaning: 'Robert Frost contemplates the tranquil peace of winter woods, yet remembers his responsibilities and the journey that lies ahead.',
      englishExplanation: 'Famous repetitive closing stanza widely memorized across generations.',
      cognitivePurpose: 'Prosodic cadence & repetitive memory anchor.',
      chunks: ['The woods are lovely, dark and deep', 'But I have promises to keep', 'And miles to go before I sleep', 'And miles to go before I sleep'],
      languageCode: 'en',
    ),
    CulturalContentItem(
      id: 'all_things_bright',
      category: 'Rhyme',
      title: 'All Things Bright and Beautiful (English)',
      originalScriptText: 'All things bright and beautiful,\nAll creatures great and small,\nAll things wise and wonderful,\nThe Lord God made them all.\nEach little flower that opens,\nEach little bird that sings.',
      transliteration: 'All things bright and beautiful, All creatures great and small, All things wise and wonderful, The Lord God made them all.',
      englishMeaning: 'Classic hymn appreciating the natural world, gentle creatures, blooming flowers, and morning melodies.',
      englishExplanation: 'Standard school assembly hymn creating effortless auditory retrieval for seniors.',
      cognitivePurpose: 'Auditory melody echo & natural category recall.',
      chunks: ['All things bright and beautiful', 'All creatures great and small', 'All things wise and wonderful', 'The Lord God made them all'],
      languageCode: 'en',
    ),
    CulturalContentItem(
      id: 'childhood_nursery_medley',
      category: 'Rhyme',
      title: 'Humpty Dumpty & Baa Baa Black Sheep (Nursery Rhymes)',
      originalScriptText: 'Humpty Dumpty sat on a wall,\nHumpty Dumpty had a great fall;\nAll the king\'s horses and all the king\'s men\nCouldn\'t put Humpty together again.\nBaa, baa, black sheep, have you any wool?\nYes, sir, yes, sir, three bags full!',
      transliteration: 'Humpty Dumpty sat on a wall, Humpty Dumpty had a great fall; All the king\'s horses and all the king\'s men...',
      englishMeaning: 'Timeless childhood rhymes activating the earliest linguistic rhythms stored in deep long-term memory.',
      englishExplanation: 'Earliest auditory childhood pathways remain remarkably intact in older adults.',
      cognitivePurpose: 'Earliest childhood auditory trace & sequential meter.',
      chunks: ['Humpty Dumpty sat on a wall', 'Humpty Dumpty had a great fall', 'All the king\'s horses and all the king\'s men', 'Couldn\'t put Humpty together again'],
      languageCode: 'en',
    ),
    CulturalContentItem(
      id: 'frost_road_not_taken',
      category: 'Poem',
      title: 'The Road Not Taken (Robert Frost)',
      originalScriptText: 'Two roads diverged in a yellow wood,\nAnd sorry I could not travel both\nAnd be one traveler, long I stood\nAnd looked down one as far as I could;\nI took the one less traveled by,\nAnd that has made all the difference.',
      transliteration: 'Two roads diverged in a yellow wood, And sorry I could not travel both And be one traveler, long I stood... I took the one less traveled by, And that has made all the difference.',
      englishMeaning: 'Reflecting on life choices with peace and acceptance, cherishing the unique path taken.',
      englishExplanation: 'Classic reflective poem providing rich philosophical grounding.',
      cognitivePurpose: 'Life narrative recall & philosophical self-reflection.',
      chunks: ['Two roads diverged in a yellow wood', 'And sorry I could not travel both', 'I took the one less traveled by', 'And that has made all the difference'],
      languageCode: 'en',
    ),
    CulturalContentItem(
      id: 'family_garden_walk',
      category: 'Story',
      title: 'Morning Garden Walk: Jasmine & Coffee (Family Memory)',
      originalScriptText: 'Walking out into the fresh morning air,\nWhite jasmine and red hibiscus in full bloom.\nListening to chirping sparrows on the wire,\nSipping hot filter coffee on the quiet veranda.\nPeace and gentle memories warm the family home.',
      transliteration: 'Walking out into the fresh morning air, White jasmine and red hibiscus in full bloom...',
      englishMeaning: 'Sensory reminiscence of tranquil Indian morning routines, fresh blossoms, and comforting hot brew.',
      englishExplanation: 'Caregiver-friendly sensory narrative connecting sight, smell, and routine recall.',
      cognitivePurpose: 'Sensory aroma/visual anchoring & calming orientation.',
      chunks: ['Walking out into the fresh morning air', 'White jasmine and red hibiscus in bloom', 'Listening to chirping sparrows on the wire', 'Sipping hot filter coffee on the quiet veranda'],
      languageCode: 'en',
    ),
  ];

  @override
  List<CulturalContentItem> getAllItems() => List.unmodifiable(_items);

  @override
  CulturalContentItem? getItemById(String id) {
    try {
      return _items.firstWhere((item) => item.id == id);
    } catch (_) {
      return null;
    }
  }
}
